In [4]:
import json

file_path = './live_reaction_PM.json'  

with open(file_path, 'r') as file:
    data = json.load(file)

with open(file_path, 'w') as file:
    json.dump(data, file, indent=4)  

print(f"Indented JSON saved to {file_path}")

Indented JSON saved to ./live_reaction_PM.json

In [3]:
import json
import pandas as pd

In [4]:
# Load both JSON files
file1_path = './wfaa_DK.json'  # Path to first file
file2_path = './wfaa_AB.json'  # Path to second file

# Load the JSON data from both files

with open(file1_path, 'r') as file1, open(file2_path, 'r') as file2:
    data1 = json.load(file1)
    data2 = json.load(file2)

# Convert to DataFrames
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [5]:
df1.head()

,timestamp,author,message
0,2024-09-10 20:55:44,Truth,"This is what Democrats do to you in court, lie..."
1,2024-09-10 20:55:48,Chocolate,@Emanuel N so is fascism
2,2024-09-10 20:55:52,Curt,facts
3,2024-09-10 20:55:56,Kaiden9226,:hundred_points::hundred_points::hundred_points:
4,2024-09-10 20:56:07,urmailman,AWWWW YEAHHHH ITS TIMEEE

In [6]:
df1.size

2787

In [7]:
df2.size

1587

In [8]:
df1['timestamp'] = pd.to_datetime(df1['timestamp'])
df2['timestamp'] = pd.to_datetime(df2['timestamp'])

# sort the dataframes by timestamp
df1 = df1.sort_values('timestamp')
df2 = df2.sort_values('timestamp')

df1.head()

,timestamp,author,message
0,2024-09-10 20:55:44,Truth,"This is what Democrats do to you in court, lie..."
1,2024-09-10 20:55:48,Chocolate,@Emanuel N so is fascism
2,2024-09-10 20:55:52,Curt,facts
3,2024-09-10 20:55:56,Kaiden9226,:hundred_points::hundred_points::hundred_points:
4,2024-09-10 20:56:07,urmailman,AWWWW YEAHHHH ITS TIMEEE

In [11]:
# define merged start and end time.
start_timestamp = min(df1["timestamp"].min(), df2["timestamp"].min())
end_timestamp = max(df1["timestamp"].max(), df2["timestamp"].max())

# pick data from start - from min(df1["timestamp"].min(), df2["timestamp"].min()) to max(df1["timestamp"].min(), df2["timestamp"].min())
start_range = (start_timestamp, max(df1["timestamp"].min(), df2["timestamp"].min()))
# pick data from end
end_range = (min(df1["timestamp"].max(), df2["timestamp"].max()), end_timestamp)

In [21]:
start_range

(Timestamp('2024-09-10 20:54:46'), Timestamp('2024-09-10 20:55:44'))

In [53]:
def merge_start(range, df1, df2):
    start_at = range[0]

    if df1["timestamp"][0] == start_at:
        # pick elements from df1 for given range
        df1 = df1[df1["timestamp"] <= range[1]]
        return df1
    else:
        # pick elements from df2 for given range
        df2 = df2[df2["timestamp"] <= range[1]]
        return df2

def merge_end(range, df1, df2):
    end_at = range[1]
    
    # compare last timestamp of df1
    if df1["timestamp"].iloc[-1] == end_at:
        # pick elements from df1 for given range
        df1 = df1[df1["timestamp"] >= range[0]]
        return df1
    else:
        # pick elements from df2 for given range
        df2 = df2[df2["timestamp"] >= range[0]]
        return df2
    
# mid_range = (start_range[1], end_range[0])

# merge from one after end of merge_start to one before start of merge_end
df_mid = df1[(df1["timestamp"] > start_range[1]) & (df1["timestamp"] < end_range[0])]

In [54]:
df_mid.head()

,timestamp,author,message
1,2024-09-10 20:55:48,Chocolate,@Emanuel N so is fascism
2,2024-09-10 20:55:52,Curt,facts
3,2024-09-10 20:55:56,Kaiden9226,:hundred_points::hundred_points::hundred_points:
4,2024-09-10 20:56:07,urmailman,AWWWW YEAHHHH ITS TIMEEE
5,2024-09-10 20:56:10,CORE KeyMaker,My nips

In [55]:
df_mid.tail()

,timestamp,author,message
524,2024-09-10 21:52:24,MeSalty,Trump 2024! :smiling_face_with_sunglasses:
525,2024-09-10 21:52:29,scar,also that entire statement was disgusting and ...
526,2024-09-10 21:52:42,scar,like bro needs to pipe down
527,2024-09-10 21:53:45,SOVEREIGNDesigns,"oh my , mow the nation is dieing . yeah becaus..."
528,2024-09-10 21:53:54,Jason Post,“YALL NEED TO THANK A UNION WORKAH” come on Ha...

In [32]:
merged_df = merge_start(start_range, df1, df2)

In [33]:
# chagne the timestamp to values
merged_df.head(1)

            timestamp         author   message
0 2024-09-10 20:54:46  Charlie Beehr  9 pm est

In [34]:
merged_df.tail(1)

,timestamp,author,message
18,2024-09-10 20:55:44,Truth,"This is what Democrats do to you in court, lie..."

In [35]:
len(merged_df)

19

In [36]:
end_range

(Timestamp('2024-09-10 21:54:13'), Timestamp('2024-09-10 22:46:37'))

In [50]:
end_merge_portion = merge_end(end_range, df1, df2)
end_merge_portion.head(1)

,timestamp,author,message
529,2024-09-10 21:54:13,jeremy shearer,Kamel toe ain’t ready… she needs to practice m...

In [51]:
end_merge_portion.tail(1)

              timestamp author            message
928 2024-09-10 22:46:37  Lindy  DISASTER ON TRUMP